#!/bin/bash


### Job Name
#SBATCH --job-name=do_exp_Turnover

### Set email type for job
### Accepted options: NONE, BEGIN, END, FAIL, ALL
#SBATCH --mail-type=END

### email address for user
###SBATCH --mail-user=None

### Queue name that job is submitted to
#SBATCH --partition=tango

### Request resources
#SBATCH --ntasks=8
#SBATCH --mem=64gb

echo Running on host `hostname`
echo Time is `date`

# our methods

python do_exp.py config/turnover.txt train_cf.py
python do_exp.py config/turnover.txt train.py


# Run the baseline methods
python do_exp.py config/turnover.txt mtlrdeep.py
python do_exp.py config/turnover.txt deepsurv.py
python do_exp.py config/turnover.txt ksvm.py
python do_exp.py config/turnover.txt survf.py


Rscript turnover_B_R.R
